name: Build Static QEMU for ARM64
on: 
  push:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build-qemu:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Build Static QEMU
      run: |
        docker run --platform linux/arm64 --rm -v /tmp:/output ubuntu:20.04 bash -c "
          apt update && 
          apt install -y build-essential wget libglib2.0-dev libpixman-1-dev pkg-config python3 ninja-build zlib1g-dev &&
          cd /tmp &&
          wget -q https://download.qemu.org/qemu-4.2.1.tar.xz &&
          tar -xf qemu-4.2.1.tar.xz &&
          cd qemu-4.2.1 &&
          ./configure --target-list=aarch64-softmmu --static --disable-vnc --disable-gtk --enable-kvm --disable-tools &&
          make -j\$(nproc) &&
          strip aarch64-softmmu/qemu-system-aarch64 &&
          cp aarch64-softmmu/qemu-system-aarch64 /output/qemu-static-arm64 &&
          echo 'Build completed!'
        "
        
    - name: Upload QEMU Binary
      uses: actions/upload-artifact@v3
      with:
        name: qemu-static-arm64
        path: /tmp/qemu-static-arm64
