name: Build QEMU 4.2.1 aarch64 Static

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 清理旧源码
      - name: Clean qemu folder
        run: rm -rf qemu

      # 拉官方 v4.2.1
      - name: Checkout QEMU v4.2.1
        uses: actions/checkout@v4
        with:
          repository: qemu/qemu
          ref: v4.2.1
          path: qemu

      # 安装交叉编译依赖
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            gcc-aarch64-linux-gnu \
            make \
            autoconf \
            libtool \
            pkg-config \
            libglib2.0-dev \
            libpixman-1-dev

      # 配置交叉静态编译（跳过 Meson）
      - name: Configure QEMU
        run: |
          cd qemu
          export PKG_CONFIG=pkg-config
          ./configure \
            --host=aarch64-linux-gnu \
            --target-list=aarch64-softmmu \
            --cross-prefix=aarch64-linux-gnu- \
            --static \
            --disable-vnc \
            --disable-gtk \
            --disable-sdl \
            --disable-spice \
            --disable-curses \
            --disable-tools \
            --disable-docs \
            --disable-strip

      # 编译并拷贝可执行文件
      - name: Build QEMU
        run: |
          cd qemu
          make -j$(nproc)
          cp aarch64-softmmu/qemu-system-aarch64 $GITHUB_WORKSPACE/

      # 上传产物
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: qemu-system-aarch64-v4.2.1-static
          path: qemu-system-aarch64
