# .github/workflows/build-static-qemu.yml
name: Build QEMU 4.2.1 Static for AArch64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clean workspace
        run: rm -rf qemu-4.2.1 qemu-4.2.1.tar.xz qemu-system-aarch64

      - name: Download QEMU 4.2.1
        run: |
          wget https://download.qemu.org/qemu-4.2.1.tar.xz
          tar xJf qemu-4.2.1.tar.xz

      - name: Install cross‐build deps
        run: |
          sudo apt update
          sudo apt install -y \
            gcc-aarch64-linux-gnu \
            pkg-config-aarch64-linux-gnu \
            libc6-dev:arm64 \
            libglib2.0-dev:arm64 \
            libpixman-1-dev:arm64 \
            make \
            autoconf \
            libtool

      - name: Debug pkg-config dirs
        run: |
          echo "Native pkg-config   : $(which pkg-config)"
          echo "Cross pkg-config    : $(which aarch64-linux-gnu-pkg-config)"
          echo "Multiarch pc files  :"
          ls -1 /usr/lib/aarch64-linux-gnu/pkgconfig

      - name: Configure & build QEMU
        run: |
          cd qemu-4.2.1

          export CROSS_COMPILE=aarch64-linux-gnu-
          export PKG_CONFIG=aarch64-linux-gnu-pkg-config
          export PKG_CONFIG_LIBDIR=/usr/lib/aarch64-linux-gnu/pkgconfig

          ./configure \
            --host=aarch64-linux-gnu \
            --target-list=aarch64-softmmu \
            --cross-prefix=${CROSS_COMPILE} \
            --static \
            --disable-vnc \
            --disable-gtk \
            --disable-sdl \
            --disable-spice \
            --disable-curses \
            --disable-tools \
            --disable-docs \
            --disable-strip

          make -j$(nproc)
          cp aarch64-softmmu/qemu-system-aarch64 $GITHUB_WORKSPACE/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: qemu-system-aarch64-v4.2.1-static
          path: qemu-system-aarch64
