name: Build QEMU 4.2.1 aarch64 Static

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clean qemu folder
        run: rm -rf qemu

      - name: Checkout QEMU v4.2.1
        uses: actions/checkout@v4
        with:
          repository: qemu/qemu
          ref: v4.2.1
          path: qemu

      - name: Install cross-compile deps
        run: |
          sudo apt update
          sudo apt install -y \
            gcc-aarch64-linux-gnu \
            make \
            autoconf \
            libtool \
            pkg-config \
            pkg-config-aarch64-linux-gnu \
            libglib2.0-dev:arm64 \
            libpixman-1-dev:arm64

      - name: Configure QEMU
        run: |
          cd qemu
          export CROSS_COMPILE=aarch64-linux-gnu-
          export PKG_CONFIG=pkg-config-aarch64-linux-gnu
          export PKG_CONFIG_LIBDIR=/usr/lib/aarch64-linux-gnu/pkgconfig
          ./configure \
            --host=aarch64-linux-gnu \
            --target-list=aarch64-softmmu \
            --cross-prefix=${CROSS_COMPILE} \
            --static \
            --disable-vnc \
            --disable-gtk \
            --disable-sdl \
            --disable-spice \
            --disable-curses \
            --disable-tools \
            --disable-docs \
            --disable-strip

      - name: Build QEMU
        run: |
          cd qemu
          make -j$(nproc)
          cp aarch64-softmmu/qemu-system-aarch64 $GITHUB_WORKSPACE/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: qemu-system-aarch64-v4.2.1-static
          path: qemu-system-aarch64
